### ISSUE TITLE
Migrate package deployments to GitHub actions

### ISSUE THREAD

**Issue by t1gor** [VISIT-X/vxpay-js#93]
cc @t1gor

## Problem
We used to have Travis CI, but it does not work any more.

## Details....
https://github.com/marketplace/actions/npm-publish#github-action
```
on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
```
